# Generated by Django 5.1.4 on 2025-03-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_review_created_at_review_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="date",
        ),
    ]
