# Generated by Django 5.1.7 on 2025-03-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_id"),
        ("product", "0002_alter_product_options_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
